services:
  s3:
    image: quay.io/minio/minio
    container_name: "s3-container"
    command: server /data --console-address ":9090"
    environment:
      - MINIO_ROOT_USER=UserParking
      - MINIO_ROOT_PASSWORD=PassWordParking
    volumes:
      - "~/minio/data:/data"
    ports:
      - "9000:9000" # Operation
      - "9090:9090" # Interface
  
  spark:
    build:
      context: ./processToDataLake
      dockerfile: Dockerfile
    container_name: "spark-container"
    depends_on:
      - s3
      - zookeeper
      - kafka
    environment:
      - SPARK_MASTER_NAME=spark-master
      - SPARK_MASTER_PORT=7077
      - SPARK_WORKER_CORES=2
      - SPARK_WORKER_MEMORY=2G
      - SPARK_DRIVER_MEMORY=2G
    ports:
      - "4040:4040" # Spark UI
      - "7077:7077" # Spark Master
      - "8081:8081" # Spark Worker UI
