{
 "title": "DashBoardParking",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Best Chance To Find Place",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT region, percentage_free_places FROM drone_data_stats LIMIT 50 "
    }
   ]
  },
  {
   "title": "Total Parking Place",
   "type": "barchart",
   "gridPos": { "h": 20, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT region, total_places FROM drone_data_stats"
    }
   ]
  },
  {
   "title": "Availability percentage",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "rawSql": "SELECT region,percentage_free_places FROM drone_data_stats "
    }
   ]
  }
 ]
}